/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _telemetry_TelemetryPacket {
    int32_t source_id;
    int32_t wind_speed;
    int32_t wind_mode;
    int32_t wind_direction;
    double latitude;
    double longitude;
    int32_t imu_sensitivity;
} telemetry_TelemetryPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define telemetry_TelemetryPacket_init_default   {0, 0, 0, 0, 0, 0, 0}
#define telemetry_TelemetryPacket_init_zero      {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define telemetry_TelemetryPacket_source_id_tag  1
#define telemetry_TelemetryPacket_wind_speed_tag 2
#define telemetry_TelemetryPacket_wind_mode_tag  3
#define telemetry_TelemetryPacket_wind_direction_tag 4
#define telemetry_TelemetryPacket_latitude_tag   5
#define telemetry_TelemetryPacket_longitude_tag  6
#define telemetry_TelemetryPacket_imu_sensitivity_tag 7

/* Struct field encoding specification for nanopb */
#define telemetry_TelemetryPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    source_id,        1) \
X(a, STATIC,   SINGULAR, INT32,    wind_speed,       2) \
X(a, STATIC,   SINGULAR, INT32,    wind_mode,        3) \
X(a, STATIC,   SINGULAR, INT32,    wind_direction,   4) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,         5) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,        6) \
X(a, STATIC,   SINGULAR, INT32,    imu_sensitivity,  7)
#define telemetry_TelemetryPacket_CALLBACK NULL
#define telemetry_TelemetryPacket_DEFAULT NULL

extern const pb_msgdesc_t telemetry_TelemetryPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define telemetry_TelemetryPacket_fields &telemetry_TelemetryPacket_msg

/* Maximum encoded size of messages (where known) */
#define TELEMETRY_TELEMETRY_PB_H_MAX_SIZE        telemetry_TelemetryPacket_size
#define telemetry_TelemetryPacket_size           55

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
